travis:
  secure:
    BINSTAR_TOKEN: mjvGHI8Mqr+M1jufhvsNQEEa9gebClmZroeeIgpwst4qi4uEAAZzh4CF6xMTUJctU8rB61IcILkLzwqUQGA4Mozqb2cIaGcXkSrfev0oys/IfWqPD8CiOCgsakipPApGJzFukbVQ/DhdXGZnQlkYA8n68fXxUcwTkAWpEKlCtbs4R8iTxjMzh3/Wqnax6piqvsEYYwAnY1KoP1x/ojZ3RJ48guT2VUVmE1yqfZfkCvyZGTGa5zcw97VhvORWxmIujCyW7s/smyUYj2FjI/kFyAgWtXbMytBnA0/cp2hnrznEwrJjLNgwrsId61euG7e1roG7cvmPX1rg3wVnAJo0mcM7ivunB6QQUkDMHojtGwoJzuZumqRbv1W2NFicWA4JOdiwm1EgwJevicJnZVOKQ1keshNYuwbTUO/K4CFaTsvUuLvfLNvDwnB6otaDCQ7fabXv5yjFEYZMWj868pLvPEdjhJCr+Ak329uAyP2NuElWhHSQtF4NaH2QT9p/NxD4pgxJzUQPh5Vm2c7jjbjdy4HF37P4chO8o2d/TI7DZfwASbQC5aPBUR9jX1kY0DwUiAOCrGovpZ+PCwR5qx+9w3z2INaHK1Mow1bJn5OGSGbIVtu6HcgdNY9RX7xyIHkN+Zu7uewhg8rh12skPo+Ivd8tcsqOjaS1FnCNc6HURSw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
